services:

  mongo:
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db/

  valkey:
    image: valkey/valkey:latest
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/usr/local/etc/valkey

volumes:
  mongodb_data:
  valkey_data: